server:
  port: 8060

spring:
  application:
    name: seata-server
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  registry:
    type: nacos
  nacos:
    server-addr: 127.0.0.1:8848
    application: seata-server
    namespace:
    username: nacos
    password: nacos
    group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      username: nacos
      password: nacos
      group: SEATA_GROUP