server:
  port: 8050

spring:
  application:
    name: sentinel

  nacos:
    discovery:
      server-addr: 127.0.0.1:8848



  cloud:
    sentinel:
      transport:
        # Sentinel 控制台地址
        dashboard: 127.0.0.1:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow