server:
  port: 3000

# Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
# Nacos认证信息

spring:
  application:
    name: login
  profiles:
    active: login-dev
  #  profiles:
#    active: dev
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
    sentinel:
      transport:
        # Sentinel 控制台地址
        dashboard: 127.0.0.1:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: 127.0.0.1:8848
            dataId: sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  datasource:
    #    name: dev
    url: jdbc:mysql://127.0.0.1:3306/cloud-dev?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    #最大链接数
    maxActive: 20
    #初始化链接数
    initialSize: 1
    #最大等候时间
    maxWait: 60000
    #最小链接数
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    #集群部署采用这里
    cluster:
#      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
      # Redis默认情况下有16个分片(库)，这里配置具体使用的分片，默认是0
      database: 0
      # redis服务器地址（填写自己的服务器地址）
      host: 127.0.0.1
      # redis端口（默认6379）
      port: 6379
      #redis连接超时等待,10秒
      timeout: PT10S
      # redis访问密码（默认为空）
      password:
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制） 默认 8
          max-active: 50
          # 连接池中的最大空闲连接 默认 8
          max-idle: 20
          # 连接池中的最小空闲连接 默认 0
          min-idle: 1
          # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认 -1，这里配置10s
          max-wait: PT10S
# mybatis-plus 配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#  config-location: classpath*:/mapper/mybatis-config.xml
  mapper-locations: classpath*:/mapper/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    # 热加载mapper文件
    refresh: true
    db-config:
      db-type: mysql

seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  registry:
    type: nacos
  nacos:
    server-addr: 127.0.0.1:8848
    application: seata-server
    namespace:
    username: nacos
    password: nacos
    group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      username: nacos
      password: nacos
      group: SEATA_GROUP
