# 应用服务 WEB 访问端口
server:
  port: 8070
spring:
  application:
    name: gateway # 应用名称
  cloud:
    # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
    # Nacos认证信息
    nacos:
      discovery:
        username: nacos
        password: nacos
        # Nacos 服务发现与注册配置，其中子属性 server-addr 指定 Nacos 服务器主机和端口
        server-addr: 127.0.0.1:8848
        namespace: public # 注册到 nacos 的指定 namespace，默认为 public
    # gateway 配置
    gateway:
      # 路由规则
      routes:
        - id: order_route # 路由的唯一标识，路由到order
          uri: lb://service-openfeign  # 需要转发的地址  lb：使用nacos本地的负载均衡策略
          # 断言规则 用于路由规则的匹配
          predicates:
            - Path=/service-order/**
          # 过滤器
          filters:
            - StripPrefix=1 #转发之前去掉第一层路由
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  registry:
    type: nacos
  nacos:
    server-addr: 127.0.0.1:8848
    application: seata-server
    namespace:
    username: nacos
    password: nacos
    group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace:
      username: nacos
      password: nacos
      group: SEATA_GROUP